import {useMemo} from 'react';
import type {Library,Game} from '@/lib/library';
import {collectionStats} from '@/lib/collection-stats';
export function CollectionDashboard({library,onBrowse,onGame,onAdd}:{library:Library;onBrowse:(label:string,games:Game[])=>void;onGame:(game:Game)=>void;onAdd:()=>void}){
 const s=useMemo(()=>collectionStats(library),[library]);
 const cards:[string,Game[],string][]=[['Owned',s.owned,'Physical or digital'],['Completed',s.completed,'Owned games marked Complete'],['Unplayed',s.backlog,'Owned backlog, not playing or complete'],['Wishlist',s.wishlist,'Games marked Wish List'],['Playing',s.playing,'Your current games'],['All games',s.total,'Every entry in your library']];
 const breakdown=(title:string,rows:typeof s.platforms)=><section className="dashboard-panel"><h2>{title}</h2><p className="muted">Owned games · select a row to explore</p>{rows.length?<div className="dashboard-bars">{rows.map(row=><button key={row.label} className="dashboard-bar" onClick={()=>onBrowse(title+': '+row.label,row.games)}><span>{row.label}</span><b>{row.games.length}</b><i aria-hidden="true" style={{width:row.games.length/Math.max(1,s.owned.length)*100+'%'}}/></button>)}</div>:<p className="dashboard-empty">Add an owned game to see this breakdown.</p>}<p className="dashboard-note">Games with multiple selections appear in each relevant row.</p></section>;
 return <section className="collection collection-dashboard">
 <p className="eyebrow">YOUR COLLECTION AT A GLANCE</p><h1>Your gaming atlas.</h1><p className="muted">A live overview of your whole library, independent of your search filters.</p>
 {!s.total.length&&<div className="dashboard-welcome"><h2>Your collection starts here.</h2><p>Add your first game or import a library from Settings. Your dashboard will fill in automatically.</p><button className="primary" onClick={onAdd}>Add your first game</button></div>}
 <div className="dashboard-totals">{cards.map(([label,games,note])=><button className="dashboard-total" key={label} onClick={()=>onBrowse(label,games)} aria-label={label+': '+games.length+' games'}><span>{label}</span><strong>{games.length}</strong><small>{note}</small></button>)}</div>
 <div className="dashboard-grid">
 <section className="dashboard-panel dashboard-completion"><h2>Making progress</h2><div className="dashboard-progress"><div className="dashboard-ring" style={{background:'conic-gradient(var(--primary) '+s.completion+'%, var(--border) 0)'}} aria-label={s.completion+' percent of owned games completed'}><strong>{s.completion}%</strong></div><div><b>{s.completed.length} of {s.owned.length} owned games completed</b><p className="muted">{s.backlog.length} in your unplayed backlog</p><button className="quiet" onClick={()=>onBrowse('No play status',s.unspecified)}>{s.unspecified.length} with no play status →</button></div></div><p className="dashboard-note">Unplayed means Backlog, excluding games also marked Complete or Currently Playing.</p><div className="dashboard-formats"><button className="quiet" onClick={()=>onBrowse('Physical',s.physical)}>Physical · {s.physical.length}</button><button className="quiet" onClick={()=>onBrowse('Digital',s.digital)}>Digital · {s.digital.length}</button></div><p className="dashboard-note">Games owned in both formats count once in Owned.</p></section>
 <section className="dashboard-panel"><h2>Highest-rated in your collection</h2><p className="muted">{s.average===null?'No scored games yet.':s.average.toFixed(1)+' / 10 average across '+s.rated.length+' scored owned games.'}</p>{s.rated.length?<ol className="dashboard-ranked">{s.rated.slice(0,5).map((entry,i)=><li key={entry.game.id}><button onClick={()=>onGame(entry.game)}><span className="dashboard-rank">{i+1}</span><strong>{entry.title}</strong><b>{entry.score.toFixed(1)}</b></button></li>)}</ol>:<p className="dashboard-empty">Scores added to your owned games will appear here.</p>}</section>
 {breakdown('By platform',s.platforms)}{breakdown('By genre',s.genres)}
 </div></section>;
}
