import {useMemo} from 'react';
import type {Library,Game} from '@/lib/library';
import {collectionStats} from '@/lib/collection-stats';
export function CollectionDashboard({library,onBrowse,onGame,onAdd}:{library:Library;onBrowse:(label:string,games:Game[])=>void;onGame:(game:Game)=>void;onAdd:()=>void}){
 const s=useMemo(()=>collectionStats(library),[library]);
 const cards:[string,Game[],string][]=[['All Games',s.total,'Every entry in your library'],['Owned Physical',s.physical,'Games you own physically'],['Owned Digital',s.digital,'Games you own digitally'],['Completed',s.completed,'Owned games marked Complete'],['Playing',s.playing,'Your current games'],['Must Play',s.mustPlay,'Your priority games'],['Replay',s.replay,'Games worth another playthrough'],['Wish List',s.wishlist,'Games you want to own'],['Upcoming',s.upcoming,'Games releasing after today']];
 const breakdown=(title:string,rows:typeof s.platforms)=><section className="dashboard-panel"><h2>{title}</h2><p className="muted">Owned games · select a row to explore</p>{rows.length?<div className="dashboard-bars">{rows.map(row=><button key={row.label} className="dashboard-bar" onClick={()=>onBrowse(title+': '+row.label,row.games)}><span>{row.label}</span><b>{row.games.length}</b><i aria-hidden="true" style={{width:row.games.length/Math.max(1,s.owned.length)*100+'%'}}/></button>)}</div>:<p className="dashboard-empty">Add an owned game to see this breakdown.</p>}<p className="dashboard-note">Games with multiple selections appear in each relevant row.</p></section>;
 return <section className="collection collection-dashboard">
 <p className="eyebrow">YOUR COLLECTION AT A GLANCE</p><h1>Your gaming atlas.</h1><p className="muted">A live overview of your whole library, independent of your search filters.</p>
 {!s.total.length&&<div className="dashboard-welcome"><h2>Your collection starts here.</h2><p>Add your first game or import a library from Settings. Your dashboard will fill in automatically.</p><button className="primary" onClick={onAdd}>Add your first game</button></div>}
 <div className="dashboard-totals">{cards.map(([label,games,note])=><button className="dashboard-total" key={label} onClick={()=>onBrowse(label,games)} aria-label={label+': '+games.length+' games'}><span>{label}</span><strong>{games.length}</strong><small>{note}</small></button>)}</div>
 <div className="dashboard-grid">
 <section className="dashboard-panel dashboard-completion"><h2>Making progress</h2><div className="dashboard-progress"><div className="dashboard-ring" style={{background:'conic-gradient(var(--primary) '+s.completion+'%, var(--border) 0)'}} aria-label={s.completion+' percent of owned games completed'}><strong>{s.completion}%</strong></div><div><b>{s.completed.length} of {s.owned.length} owned games completed</b><p className="muted">{s.backlog.length} waiting to be played</p><button className="quiet" onClick={()=>onBrowse('No play status',s.unspecified)}>{s.unspecified.length} with no play status →</button></div></div><p className="dashboard-note">Unplayed uses Must Play (and older Backlog entries), excluding games also marked Complete or Currently Playing.</p><div className="dashboard-formats"><button className="quiet" onClick={()=>onBrowse('Physical',s.physical)}>Physical · {s.physical.length}</button><button className="quiet" onClick={()=>onBrowse('Digital',s.digital)}>Digital · {s.digital.length}</button></div><p className="dashboard-note">Games owned in both formats count once in Owned.</p></section>
 <section className="dashboard-panel dashboard-average"><h2>Average collection score</h2>{s.average===null?<p className="dashboard-empty">No scored games yet. Add scores to your owned games to see your collection average.</p>:<figure className="dashboard-average-chart"><div className="dashboard-ring dashboard-score-ring" role="img" aria-label={s.average.toFixed(1)+' out of 10 average score'} style={{background:'conic-gradient(var(--primary) '+(s.average*10)+'%, var(--border) 0)'}}><strong aria-hidden="true">{s.average.toFixed(1)}<small>/ 10</small></strong></div><figcaption className="muted">{s.average.toFixed(1)} / 10 average across {s.rated.length} scored owned {s.rated.length===1?'game':'games'}.</figcaption></figure>}</section>
 <section className="dashboard-panel dashboard-unplayed"><h2>Highest-rated unplayed games</h2><p className="muted">Your highest-scored owned games marked Must Play.</p>{s.unplayedRated.length?<><ol className="dashboard-ranked">{s.unplayedRated.slice(0,5).map((entry,i)=><li key={entry.game.id}><button onClick={()=>onGame(entry.game)}><span className="dashboard-rank">{i+1}</span><strong>{entry.title}</strong><b>{entry.score.toFixed(1)}</b></button></li>)}</ol><button className="quiet dashboard-more" onClick={()=>onBrowse('Rated unplayed games',s.unplayedRated.map(r=>r.game))}>Browse all {s.unplayedRated.length} rated unplayed games →</button></>:<p className="dashboard-empty">Mark owned games as Must Play and add scores to see your next great games here.</p>}</section>
 <section className="dashboard-panel dashboard-developers"><h2>Favorite developers</h2><p className="muted">Most represented Studio credits in your owned collection.</p>{s.developers.length?<ol className="dashboard-ranked">{s.developers.slice(0,5).map((row,i)=><li key={row.label}><button onClick={()=>onBrowse('Studio: '+row.label,row.games)}><span className="dashboard-rank">{i+1}</span><strong>{row.label}<small className="dashboard-credit-score">{row.average===null?'No scored games':row.average.toFixed(1)+' / 10 average · '+row.ratedCount+' scored'}</small></strong><b>{row.games.length} games</b></button></li>)}</ol>:<p className="dashboard-empty">Add Studio credits to your owned games to discover your most-collected developers.</p>}<p className="dashboard-note">Uses Studio exactly as entered; combined credits stay together. Averages exclude missing scores.</p>{!!s.noStudio.length&&<button className="quiet dashboard-more" onClick={()=>onBrowse('Missing Studio credits',s.noStudio)}>{s.noStudio.length} owned games without Studio credits →</button>}</section>
 <section className="dashboard-panel dashboard-wishlist"><h2>Wishlist priorities</h2><p className="muted">{s.wishlist.length} games on your wishlist · choose a group to browse</p>{s.wishlist.length?<><div className="dashboard-bars">{s.wishlistPriorities.map(row=><button key={row.label} className="dashboard-bar" onClick={()=>onBrowse('Wishlist: '+row.label,row.games)}><span>{row.label}</span><b>{row.games.length}</b><i aria-hidden="true" style={{width:row.games.length/Math.max(1,s.wishlist.length)*100+'%'}}/></button>)}</div><div className="dashboard-wishlist-dates">{([['Already released',s.releaseGroups.released],['Upcoming',s.releaseGroups.upcoming],['Date not set',s.releaseGroups.unknown]] as [string,Game[]][]).map(([label,games])=><button className="quiet" key={label} onClick={()=>onBrowse('Wishlist: '+label,games)}>{label} · {games.length}</button>)}</div><p className="dashboard-note">Dates use your saved release information, not a live release check. Games with multiple priorities appear in each selected group.</p></>:<p className="dashboard-empty">Mark games as Wish List, then choose their Wishlist Priority to see them here.</p>}</section>
 {breakdown('By platform',s.platforms)}{breakdown('By genre',s.genres)}
 </div></section>;
}
