import {plain,normalizeTitle} from './game-lookup';
export const esrbOptions=['EC — Early Childhood','E — Everyone','E10+ — Everyone 10+','T — Teen','M — Mature 17+','AO — Adults Only 18+','K-A — Kids to Adults (legacy)','RP — Rating Pending','Not rated','Pre-ESRB release','Unknown'];
export const esrbLabels:Record<string,string>={EC:esrbOptions[0],E:esrbOptions[1],'E10+':esrbOptions[2],T:esrbOptions[3],M:esrbOptions[4],AO:esrbOptions[5],'K-A':esrbOptions[6],RP:esrbOptions[7]};
export function esrbRank(value:unknown){const ranks:Record<string,number>={EC:0,E:1,'K-A':1,'E10+':2,T:3,M:4,AO:5};return ranks[String(value||'').split(' — ')[0]]??99;}
export function compareEsrb(a:unknown,b:unknown,descending=false){const x=esrbRank(a),y=esrbRank(b);return x===99||y===99?(x===y?String(a||'Unknown').localeCompare(String(b||'Unknown')):x===99?1:-1):(x-y)*(descending?-1:1);}
export type EsrbMatch={title:string;platforms:string[];rating:string;url:string};
export function parseEsrb(html:string):EsrbMatch[]{return html.split('<div class="game">').slice(1).flatMap(block=>{const heading=block.match(/<h2><a href="(https:\/\/www\.esrb\.org\/ratings\/[^"<>]+)">([\s\S]*?)<\/a><\/h2>/);const code=block.match(/alt="(EC|E10\+|E|T|M|AO|K-A|RP)"/);const platforms=block.match(/<div class="platforms">([\s\S]*?)<\/div>/);return heading&&code&&platforms?[{title:plain(heading[2]),url:heading[1],rating:esrbLabels[code[1]],platforms:plain(platforms[1]).split(',').map(s=>s.trim())}]:[];});}
const platformKey=(s:string)=>{const n=normalizeTitle(s);return ({steam:'pc',windowspc:'pc',windows:'pc',xboxog:'xbox',xboxseriesx:'xboxseries',xboxseriess:'xboxseries',nintendo3ds:'3ds',nintendods:'ds',switch:'nintendoswitch',switch2:'nintendoswitch2',gameboyadvance:'gameboyadvance',gameboygameboycolor:'gameboycolor',supernintendo:'snes',playstationpsone:'playstation',nintendoentertainmentsystem:'nes',gameboycolor:'gameboycolor',gameboy:'gameboycolor',playstationvr:'playstation4',playstation1:'playstation',n64:'nintendo64',gamecube:'gamecube',nintendogamecube:'gamecube',wiiu:'wiiu'} as Record<string,string>)[n]||n;};
export function chooseEsrb(matches:EsrbMatch[],titles:string[],platforms:string[]):EsrbMatch|undefined{const keys=titles.map(normalizeTitle);const exact=matches.filter(m=>keys.includes(normalizeTitle(m.title))&&platforms.some(p=>m.platforms.some(mp=>platformKey(p)===platformKey(mp))));return exact.length&&new Set(exact.map(m=>m.rating)).size===1?exact[0]:undefined;}
export async function searchEsrbPage(title:string,page=1):Promise<{matches:EsrbMatch[];total:number}>{const response=await fetch('https://www.esrb.org/wp-admin/admin-ajax.php',{method:'POST',body:new URLSearchParams({action:'search_rating','args[searchKeyword]':title,'args[pg]':String(page)}),signal:AbortSignal.timeout(15000),redirect:'error'});if(!response.ok)throw Error('ESRB lookup unavailable ('+response.status+').');const result=await response.json();return {matches:parseEsrb(String(result.html_results||'')),total:Number(result.total)||0};}
export async function searchEsrb(title:string,page=1):Promise<EsrbMatch[]>{const response=await fetch('https://www.esrb.org/search/?'+new URLSearchParams({searchKeyword:title,pg:String(page)}),{signal:AbortSignal.timeout(15000),headers:{'User-Agent':'GameAtlas/1.7 (game collection rating lookup)'},redirect:'error'});if(!response.ok)throw Error('ESRB lookup unavailable ('+response.status+').');const html=await response.text();if(html.length>3000000)throw Error('ESRB response too large.');return parseEsrb(html);}

export function withEsrb(library:import('./library').Library){const next=structuredClone(library);if(!next.fields.some(f=>f.id==='ESRB'))next.fields.splice(next.fields.findIndex(f=>f.id==='Score')+1,0,{id:'ESRB',name:'ESRB rating',type:'text',options:esrbOptions});for(const game of next.games)if(!game.values.ESRB)game.values.ESRB='Unknown';return next;}
